### ISSUE TITLE
Performance test: ~2.5s to add 10,000 objects to an array

### ISSUE THREAD

**Issue by mrkev** [coolsoftwaretyler/mst-performance-testing#26]
This issue is a follow-up to the replies to [this tweet](https://twitter.com/aykev/status/1719588611413426608). I added `10,000` objects to an array, and on my it took about ~`2.50s`.

I'm using:

```
Chrome 118.0.5993.117 (Official Build) (arm64)
16GB, M1 Macbook Pro (2020)
```

Here is a sample trace:
[Trace-20231031T225959.json](https://github.com/coolsoftwaretyler/mst-performance-testing/files/13223942/Trace-20231031T225959.json)

The code I used to add 10,000 objects to an array is this:

```tsx
import { types } from "mobx-state-tree";
import { nanoid } from "nanoid";

const Bus = types.model({
  name: types.string,
  id: types.string,
});

const BusLine = types
  .model({
    distance: 0,
    stops: 0,
    buses: types.array(Bus),
  })
  .actions((self) => ({
    addBus(name: string) {
      self.buses.push({ name, id: nanoid(5) });
    },
  }));

const store = BusLine.create();

export function MSTTest() {
  return (
    <>
      <div>
        <button
          onClick={() => {
            performance.mark("1");
            for (let i = 0; i < 10000; i++) {
              store.addBus("hello world");
            }
            performance.mark("2");
            performance.measure("Add 10000 items", "1", "2");
            console.log("ADDED 10000");
          }}
        >
          Add 10000
        </button>
      </div>
    </>
  );
}

```

**Comment by mrkev** [comment]
Do note that I didn't write this to try and be as optimal as possible, nor to make it the most helpful test for debugging performance issues. I wrote this to get a comparison with the other state management library I'm tested on the tweet.

For example, I generate an id for every object, which in isolation is noise, but in the context on my test and application was necessary, since I do need an id, and I generate them on the test where I use the other library.

Out of curiosity I ran a version of it that doesn't generate ids and the difference is trivial.

![image](https://github.com/coolsoftwaretyler/mst-performance-testing/assets/1285131/56849a54-ec8f-4ffe-b36e-717becc5d7a8)

**Comment by coolsoftwaretyler** [comment]
@mrkev thank you so much! I will adapt this into the existing benchmarks. I'm sure your own state library will keep your hands full, but let me know if you ever want to talk shop about MST/state management performance.

We'll get these numbers down. Reproduction steps like this are very helpful to diagnosing issues and proving solutions!
